apiVersion: apps/v1
kind: Deployment
metadata:
  name: shadow-server
  namespace: shadow-ot
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: shadow-server
          image: ghcr.io/psavelis/shadow-ot/server:stable
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "8Gi"
              cpu: "6000m"
