apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shadow-ot

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment-server.yaml
  - service.yaml
  - ingress.yaml
  - database.yaml
  - deployment-web.yaml
  - monitoring.yaml

commonLabels:
  app.kubernetes.io/part-of: shadow-ot-platform
  app.kubernetes.io/managed-by: kustomize
