apiVersion: v1
kind: Service
metadata:
  name: shadow-server
  namespace: shadow-ot
  labels:
    app.kubernetes.io/name: shadow-server
spec:
  type: ClusterIP
  ports:
    - name: login
      port: 7171
      targetPort: 7171
      protocol: TCP
    - name: game
      port: 7172
      targetPort: 7172
      protocol: TCP
    - name: api
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: websocket
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app.kubernetes.io/name: shadow-server
---
apiVersion: v1
kind: Service
metadata:
  name: shadow-server-external
  namespace: shadow-ot
  labels:
    app.kubernetes.io/name: shadow-server
  annotations:
    external-dns.alpha.kubernetes.io/hostname: game.shadow-ot.com
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: login
      port: 7171
      targetPort: 7171
      protocol: TCP
    - name: game
      port: 7172
      targetPort: 7172
      protocol: TCP
  selector:
    app.kubernetes.io/name: shadow-server
---
apiVersion: v1
kind: Service
metadata:
  name: shadow-web
  namespace: shadow-ot
  labels:
    app.kubernetes.io/name: shadow-web
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: shadow-web
---
apiVersion: v1
kind: Service
metadata:
  name: shadow-web-external
  namespace: shadow-ot
  labels:
    app.kubernetes.io/name: shadow-web
  annotations:
    external-dns.alpha.kubernetes.io/hostname: shadow-ot.com
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: shadow-web
---
apiVersion: v1
kind: Service
metadata:
  name: shadow-admin-external
  namespace: shadow-ot
  labels:
    app.kubernetes.io/name: shadow-admin
  annotations:
    external-dns.alpha.kubernetes.io/hostname: admin.shadow-ot.com
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      targetPort: 3001
      protocol: TCP
  selector:
    app.kubernetes.io/name: shadow-admin
---
apiVersion: v1
kind: Service
metadata:
  name: shadow-download
  namespace: shadow-ot
  labels:
    app.kubernetes.io/name: shadow-download
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: shadow-download
