apiVersion: apps/v1
kind: Deployment
metadata:
  name: shadow-web
  namespace: shadow-ot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: shadow-web
          image: ghcr.io/psavelis/shadow-ot/web:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shadow-admin
  namespace: shadow-ot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: shadow-admin
          image: ghcr.io/psavelis/shadow-ot/admin:latest
