apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shadow-ot-dev

resources:
  - ../../base

patches:
  - path: deployment-server-patch.yaml
  - path: deployment-web-patch.yaml
  - path: ingress-patch.yaml
  - path: service-nodeports-patch.yaml
  - target:
      version: v1
      kind: Deployment
      name: shadow-download
      namespace: shadow-ot-dev
    path: deployment-download-jsonpatch.yaml

labels:
  - pairs:
      environment: dev
