apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shadow-ot-dev

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-server-patch.yaml
  - deployment-web-patch.yaml
  - ingress-patch.yaml
  - service-nodeports-patch.yaml

patchesJson6902:
  - target:
      version: v1
      kind: Deployment
      name: shadow-download
      namespace: shadow-ot-dev
    path: deployment-download-jsonpatch.yaml

commonLabels:
  environment: dev
