apiVersion: v1
kind: Service
metadata:
  name: shadow-web-external
  namespace: shadow-ot
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: shadow-admin-external
  namespace: shadow-ot
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      targetPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: shadow-server-external
  namespace: shadow-ot
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: login
      port: 7171
      targetPort: 7171
    - name: game
      port: 7172
      targetPort: 7172
---
apiVersion: v1
kind: Service
metadata:
  name: shadow-download
  namespace: shadow-ot
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      targetPort: 80
