apiVersion: v1
kind: Service
metadata:
  name: shadow-web-external
  namespace: shadow-ot
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: shadow-admin-external
  namespace: shadow-ot
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3001
      nodePort: 30081
---
apiVersion: v1
kind: Service
metadata:
  name: shadow-server-external
  namespace: shadow-ot
spec:
  type: NodePort
  ports:
    - name: login
      port: 7171
      targetPort: 7171
      nodePort: 31771
    - name: game
      port: 7172
      targetPort: 7172
      nodePort: 31772
---
apiVersion: v1
kind: Service
metadata:
  name: shadow-download
  namespace: shadow-ot
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30082
