apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shadow-ot-staging

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-server-patch.yaml
  - deployment-web-patch.yaml

commonLabels:
  environment: staging
